name: 'Release composite action'
description: 'A composite action to handle git tag and github release'

inputs:
  token:
    required: false
    description: 'A token to access private github repos'
  new_tag:
    required: true
    description: 'The new tag to push'
  prerelease:
    required: true
    description: 'Whether the release is a pre-release or not'
  namespace:
    required: true
    description: 'The package namespace'
    
outputs:
  url:
    value: ${{ steps.release.outputs.url }}

runs:
    using: "composite"
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2

      - name: git config
        shell: bash
        run: |
          git config user.email "Tevel GitHub Runner"
          git config user.name "Tevel GitHub Runner"

      # note: adding a message would create an annotated tag
      - name: Create Tag
        shell: bash
        run: |
          if [ -n ${{ inputs.new_tag }} ]; then
            if [ '${{ inputs.prerelease }}' = 'true' ]; then
              git tag ${{ inputs.new_tag }} &&
              git push --force origin ${{ inputs.new_tag }} &&
              echo "New lightweight tag: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/${{ inputs.new_tag }}"
            else
              git tag -a ${{ inputs.new_tag }} -m "${{ github.event.head_commit.message }}" &&
              git push --force origin ${{ inputs.new_tag }} &&
              echo "New annotated tag: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/${{ inputs.new_tag }}"
            fi
          fi

      - name: Create a GitHub release
        id: release
    #         if: ${{ inputs.new_tag }}
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
        with:
          prerelease: ${{ inputs.prerelease }}
          tag_name: ${{ inputs.new_tag }}
          name: Release ${{ inputs.new_tag }}
          body: |
            Docker pull command:
            <pre><code> docker pull jfrog.local:8081/reg/${{ inputs.namespace }}/${{ github.event.repository.name }}:${{ inputs.new_tag }} </code></pre>

      - name: set warning
        shell: bash
        run: |
          STRING="New release: ${{ steps.release.outputs.url }}
          Docker pull command:
          docker pull jfrog.local:8081/reg/${{ inputs.namespace }}/${{ github.event.repository.name }}:${{ inputs.new_tag }}"
          STRING="${STRING//'%'/'%25'}"
          STRING="${STRING//$'\n'/'%0A'}"
          STRING="${STRING//$'\r'/'%0D'}"
          echo "::warning::$STRING"
