name: 'Release composite action'
description: 'A composite action to handle git tag and github release'

inputs:
  token:
    required: false
    description: 'A token to access private github repos'
  new-tag:
    required: true
    description: 'The new tag to push'
  prerelease:
    required: true
    description: 'Whether the release is a pre-release or not'
  changelog:
    required: false
    description: 'The release changelog'
  files:
    required: false
    description: 'Files to add to the release'
  body:
    required: false
    description: 'Text to add to the release body'
  warning:
    required: false
    description: 'Text to add to workflow warning'
  error:
    required: false
    description: 'Text to add to workflow error'
  notice:
    required: false
    description: 'Text to add to workflow notice'
    
outputs:
  url:
    description: 'The release url'
    value: ${{ steps.release.outputs.url }}

runs:
    using: "composite"
    steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - name: Checkout
#         uses: actions/checkout@v2
      - name: workspace
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          git config --global --add safe.directory $GITHUB_WORKSPACE
      - name: git config
        shell: bash
        run: |
          git config user.email "Tevel GitHub Runner"
          git config user.name "Tevel GitHub Runner"
          lfs_config=$(echo "lfs.$GITHUB_SERVER/$GITHUB_REPOSITORY.git/info/lfs.locksverify")
          git config $lfs_config false

      # note: adding a message would create an annotated tag
      - name: Create Tag
        shell: bash
        run: |
          if [ -n ${{ inputs.new-tag }} ]; then
            if [ '${{ inputs.prerelease }}' = 'true' ]; then
              git tag ${{ inputs.new-tag }}
              git push --force origin ${{ inputs.new-tag }}
              echo "New lightweight tag: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/${{ inputs.new-tag }}"
            else
              git tag -a ${{ inputs.new-tag }} -m "${{ github.event.head_commit.message }}"
              git push --force origin ${{ inputs.new-tag }}
              echo "New annotated tag: $GITHUB_SERVER_URL/$GITHUB_REPOSITORY/releases/tag/${{ inputs.new-tag }}"
            fi
          fi

      - name: Create a GitHub release
        id: release
    #         if: ${{ inputs.new-tag }}
        uses: softprops/action-gh-release@v2
#         env:
#           GITHUB_TOKEN: ${{ inputs.token }}
        with:
#           token: ${{ inputs.token }}
          prerelease: ${{ inputs.prerelease }}
          tag_name: ${{ inputs.new-tag }}
          name: Release ${{ inputs.new-tag }}
          files: ${{ inputs.files }}
          body: |
            ${{ inputs.body }}
            ${{ inputs.changelog }}

      - name: set warning
        if: ${{ inputs.warning }}
        shell: bash
        run: |
          WARNING="
          ${{ inputs.warning }}
          "
          WARNING="${WARNING//'%'/'%25'}"
          WARNING="${WARNING//$'\n'/'%0A'}"
          WARNING="${WARNING//$'\r'/'%0D'}"
          echo "::warning::$WARNING"
          
      - name: set error
        if: ${{ inputs.error }}
        shell: bash
        run: |
          ERROR="
          ${{ inputs.error }}
          "
          ERROR="${ERROR//'%'/'%25'}"
          ERROR="${ERROR//$'\n'/'%0A'}"
          ERROR="${ERROR//$'\r'/'%0D'}"
          echo "::error::$ERROR"
          
      - name: set notice
        shell: bash
        run: |
          NOTICE="New release: ${{ steps.release.outputs.url }}
          ${{ inputs.notice }}
          "
          NOTICE="${NOTICE//'%'/'%25'}"
          NOTICE="${NOTICE//$'\n'/'%0A'}"
          NOTICE="${NOTICE//$'\r'/'%0D'}"
          echo "::notice::$NOTICE"
